services:
  reverse-proxy:
    container_name: ycbr.reverse-proxy
    image: nginx:alpine
    volumes:
      - ./nginx-reverse-proxy/templates:/etc/nginx/templates
      - ./certs/cert.pem:/etc/nginx/ssl/certfile.pem
      - ./certs/key.pem:/etc/nginx/ssl/keyfile.pem
    ports:
      - ${REVERSE_PROXY_PORT}:${REVERSE_PROXY_PORT}
    mem_limit: 64m
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "LOCALHOST_NAME:host-gateway"
    environment:
      NGINX_APP_HOST: LOCALHOST_NAME
      NGINX_APP_PORT: ${REVERSE_PROXY_PORT}
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    networks:
      - frontend
      - backend

  postgres:
    container_name: ycbr.db
    image: postgres:18-alpine
    restart: always
    ports:
      - 5432:5432
    mem_limit: 64m
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${PGUSER}
      LANG: sv_FI.utf8
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ycbr -U ycbr"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
    - ./db-data/:/var/lib/postgresql
#    - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
    extra_hosts:
    - "host.docker.internal:host-gateway"
    - "LOCALHOST_NAME:host-gateway"
    networks:
      - backend

  keycloak:
    container_name: ycbr.auth
    image: quay.io/keycloak/keycloak:24.0.0
    command:
    - start-dev
    - --import-realm
    - --features=login2
    ports:
    - 8080:8080
    - 8443:8443
    volumes:
      - ./keycloak/import/:/opt/keycloak/data/import/
      - ./certs/cert.pem:/opt/keycloak/conf/certfile.pem
      - ./certs/key.pem:/opt/keycloak/conf/keyfile.pem
    mem_limit: 1280m
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTPS_PORT: 8443
      KC_HOSTNAME_URL: https://LOCALHOST_NAME:${REVERSE_PROXY_PORT}/auth
      KC_HOSTNAME_ADMIN_URL: https://LOCALHOST_NAME:${REVERSE_PROXY_PORT}/auth
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      #KC_HOSTNAME_ENABLED: true
      KC_HTTP_RELATIVE_PATH: /auth/
      KC_HTTP_ENABLED: true
      KC_HTTPS_CERTIFICATE_FILE: '/opt/keycloak/conf/certfile.pem'
      KC_HTTPS_CERTIFICATE_KEY_FILE: '/opt/keycloak/conf/keyfile.pem'
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      #KC_LOG_LEVEL: DEBUG
    extra_hosts:
    - "host.docker.internal:host-gateway"
    - "LOCALHOST_NAME:host-gateway"
    healthcheck:
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/auth/health/live']
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - backend

  ui:
    container_name: ycbr.ui
    image: ycbr/ui
    mem_limit: 64m
    ports:
      - 7084:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "LOCALHOST_NAME:host-gateway"
    networks:
      - frontend

  api-server:
    container_name: ycbr.api-server
    image: ycbr/api-server
    ports:
    - 7082:7082
    mem_limit: 1024m
    volumes:
      - ./certs/cert.pem:/opt/certfile.pem
      - ./certs/key.pem:/opt/keyfile.pem
    environment:
      SPRING_PROFILES_ACTIVE: docker,ssl
      HOSTNAME: LOCALHOST_NAME
      REVERSE_PROXY_PORT: ${REVERSE_PROXY_PORT}
      SERVER_ADDRESS: 0.0.0.0
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${PGUSER}
    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_healthy
    extra_hosts:
    - "host.docker.internal:host-gateway"
    - "LOCALHOST_NAME:host-gateway"
    networks:
      - backend

  bff-server:
    container_name: ycbr.bff-server
    image: ycbr/bff-server
    ports:
    - 7081:7081
    mem_limit: 1024m
    volumes:
      - ./certs/cert.pem:/opt/certfile.pem
      - ./certs/key.pem:/opt/keyfile.pem
    environment:
      SPRING_PROFILES_ACTIVE: docker,ssl
      HOSTNAME: LOCALHOST_NAME
      REVERSE_PROXY_PORT: ${REVERSE_PROXY_PORT}
      SERVER_ADDRESS: 0.0.0.0
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
    depends_on:
      keycloak:
        condition: service_healthy
    extra_hosts:
    - "host.docker.internal:host-gateway"
    - "LOCALHOST_NAME:host-gateway"
    networks:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    mem_limit: 64m
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - ./monitoring/prometheus/prom_data:/prometheus
    networks:
      - backend

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    mem_limit: 64m
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./monitoring/grafana:/etc/grafana/provisioning/datasources
    networks:
      - backend

networks:
  frontend:
  backend:
