volumes:
   baeldung_bff_keycloak_postgres_data:

services:

  nginx-reverse-proxy:
    container_name: ycbr.nginx-reverse-proxy
    image: ycbr/nginx-reverse-proxy
    ports:
    - 7080:7080
    mem_limit: 64m
    extra_hosts:
    - "host.docker.internal:host-gateway"
    - "LOCALHOST_NAME:host-gateway"

#  reverse-proxy:
#    container_name: ycbr.reverse-proxy
#    image: ycbr/reverse-proxy
#    ports:
#      - 7080:7080
#    environment:
#      SPRING_PROFILES_ACTIVE: docker
#      HOSTNAME: LOCALHOST_NAME
#      SERVER_ADDRESS: 0.0.0.0
#    depends_on:
#      keycloak:
#        condition: service_healthy
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#      - "LOCALHOST_NAME:host-gateway"


  postgres:
    container_name: ycbr.db
    image: postgres:18-alpine
    restart: always
    ports:
      - 5432:5432
    mem_limit: 64m
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${PGUSER}
      LANG: sv_FI.utf8
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ycbr -U ycbr"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    volumes:
    - ./db-data/:/var/lib/postgresql
#    - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
    extra_hosts:
    - "host.docker.internal:host-gateway"
    - "LOCALHOST_NAME:host-gateway"

  keycloak:
    container_name: ycbr.auth
    image: quay.io/keycloak/keycloak:24.0.0
    command:
    - start-dev
    - --import-realm
    - --features=login2
    ports:
    - 8080:8080
    volumes:
      - ./keycloak/import/:/opt/keycloak/data/import/
    mem_limit: 1280m
    environment:
#      KC_DB: postgres
#      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
#      KC_DB_SCHEMA: public
#      KC_DB_USERNAME: keycloak
#      KC_DB_PASSWORD: secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_PORT: 8080
      KC_HOSTNAME_URL: http://LOCALHOST_NAME:7080/auth
      KC_HOSTNAME_ADMIN_URL: http://LOCALHOST_NAME:7080/auth
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      #KC_HOSTNAME_DEBUG: true
      KC_HTTP_RELATIVE_PATH: /auth/
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      #KC_LOG_LEVEL: DEBUG
    extra_hosts:
    - "host.docker.internal:host-gateway"
    - "LOCALHOST_NAME:host-gateway"
#    depends_on:
#      postgres-keycloak:
#        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:8080/auth/health/live']
      interval: 5s
      timeout: 5s
      retries: 20

#  native-ui:
#    container_name: ycbr.native-ui
#    image: ycbr/native-ui
#    ports:
#      - 4204:4204
#    extra_hosts:
#      - "host.docker.internal:host-gateway"
#      - "LOCALHOST_NAME:host-gateway"

  ui:
    container_name: ycbr.ui
    image: ycbr/ui
    mem_limit: 64m
    ports:
      - 4206:80
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "LOCALHOST_NAME:host-gateway"

  api-server:
    container_name: ycbr.api-server
    image: ycbr/api-server
    ports:
    - 7085:7085
    mem_limit: 64m
    environment:
      SPRING_PROFILES_ACTIVE: docker #,auth0
      HOSTNAME: LOCALHOST_NAME
      SERVER_ADDRESS: 0.0.0.0
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      PGUSER: ${PGUSER}
#      AUTH0_ISSUER: ${AUTH0_ISSUER}
#      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_healthy
    extra_hosts:
    - "host.docker.internal:host-gateway"
    - "LOCALHOST_NAME:host-gateway"

  bff-server:
    container_name: ycbr.bff-server
    image: ycbr/bff-server
    ports:
    - 7081:7081
    mem_limit: 64m
    environment:
      SPRING_PROFILES_ACTIVE: docker #,auth0
      HOSTNAME: LOCALHOST_NAME
      SERVER_ADDRESS: 0.0.0.0
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
#      AUTH0_ISSUER: ${AUTH0_ISSUER}
#      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
#      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
#      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
    depends_on:
      keycloak:
        condition: service_healthy
    extra_hosts:
    - "host.docker.internal:host-gateway"
    - "LOCALHOST_NAME:host-gateway"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    mem_limit: 64m
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
      - ./monitoring/prometheus/prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    mem_limit: 64m
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./monitoring/grafana:/etc/grafana/provisioning/datasources
