# Custom properties to ease configuration overrides
# on command-line or IDE launch configurations
scheme: http
hostname: localhost
reverse-proxy-port: 7080
reverse-proxy-uri: ${scheme}://${hostname}:${reverse-proxy-port}
authorization-server-prefix: /auth
issuer: ${reverse-proxy-uri}${authorization-server-prefix}/realms/ycbr
client-id: ${KEYCLOAK_CLIENT_ID:ycbr-confidential}
client-secret: ${KEYCLOAK_CLIENT_SECRET:secret}
username-claim-json-path: $.preferred_username
authorities-json-path: $.realm_access.roles
bff-port: 7081
bff-prefix: /bff
api-server-port: 7082
audience:

server:
  port: ${bff-port}
  ssl:
    enabled: false

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: bff
            uri: ${scheme}://${hostname}:${api-server-port}
            predicates:
              - Path=/api/**
            filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
              - TokenRelay=
              - SaveSession
              - StripPrefix=1
          - id: direct-access
            uri: ${scheme}://${hostname}:${api-server-port}
            predicates:
              - Path=/resources/**
  security:
    oauth2:
      client:
        provider:
          ycbr:
            issuer-uri: ${issuer}
        registration:
          ycbr:
            provider: ycbr
            authorization-grant-type: authorization_code
            client-id: ${client-id}
            client-secret: ${client-secret}
            scope: openid,profile,email,offline_access

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
        - iss: ${issuer}
          authorities:
          - path: ${authorities-json-path}
          aud: ${audience}
        # SecurityFilterChain with oauth2Login() (sessions and CSRF protection enabled)
        client:
          client-uri: ${reverse-proxy-uri}${bff-prefix}
          security-matchers:
            - /api/**
            - /login/**
            - /oauth2/**
            - /logout/**
          permit-all:
            - /api/**
            - /login/**
            - /oauth2/**
            - /logout/connect/back-channel/ycbr
          post-logout-redirect-host: ${reverse-proxy-uri}
          # post-logout-redirect-host: ${hostname}
          csrf: cookie-accessible-from-js
          oauth2-redirections:
            rp-initiated-logout: ACCEPTED
          back-channel-logout:
            enabled: true
            # internal-logout-uri: ${reverse-proxy-uri}${bff-prefix}/logout
            # should work too,  but there is no reason to go through the reverse proxy for this internal call
            internal-logout-uri: ${scheme}://${hostname}:${bff-port}/logout
        # SecurityFilterChain with oauth2ResourceServer() (sessions and CSRF protection disabled)
        resourceserver:
          permit-all:
            - /login-options
            - /error
            - /v1/api-docs/**
            - /swagger-ui/**
            - /actuator/info
            - /actuator/health
            - /actuator/health/readiness
            - /actuator/health/liveness
            - /actuator/prometheus

management:
  endpoint:
    health:
      probes:
        enabled: true
        show-details: always
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    root: INFO
    fi.smartbass.ycbr: DEBUG
    com.c4-soft.springaddons: DEBUG
    org:
      springframework:
        boot: INFO
        cloud: INFO
        security: DEBUG
        web: INFO

---
spring:
  config:
    activate:
      on-profile: docker
  main:
    banner-mode: off

---
spring:
  config:
    activate:
      on-profile: ssl
server:
  ssl:
    enabled: true
scheme: https

---
spring:
  config:
    activate:
      on-profile: cognito
issuer: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_RzhmgLwjl
client-id: 12olioff63qklfe9nio746es9f
client-secret: change-me
username-claim-json-path: username
authorities-json-path: $.cognito:groups
com:
  c4-soft:
    springaddons:
      oidc:
        client:
          oauth2-logout:
            ycbr:
              uri: https://spring-addons.auth.us-west-2.amazoncognito.com/logout
              client-id-request-param: client_id
              post-logout-uri-request-param: logout_uri

---
spring:
  config:
    activate:
      on-profile: auth0
issuer: ${AUTH0_ISSUER:https://dev-xyz.us.auth0.com/}
client-id: ${AUTH0_CLIENT_ID:YOUR_CLIENT_ID}
client-secret: ${AUTH0_CLIENT_SECRET:YOUR_CLIENT_SECRET}
username-claim-json-path: $['https://smartbass-ycbr/user']['name']
authorities-json-path: $['https://smartbass-ycbr/user']['roles']
audience: ${AUTH0_AUDIENCE:https://api.ycbr.example.com/}
com:
  c4-soft:
    springaddons:
      oidc:
        client:
          authorization-params:
            ycbr:
              audience: ${audience}
          oauth2-logout:
            ycbr:
              uri: ${issuer}v2/logout
              client-id-request-param: client_id
              post-logout-uri-request-param: returnTo